#!/bin/bash
# presumes nomad service-init has already been run
sudo cp ./nomad/client.hcl /etc/nomad.d/
sudo cp ./nomad/consul.hcl /etc/nomad.d/
sudo cp ./nomad/nomad.hcl /etc/nomad.d/
sudo cp ./nomad/telemetry.hcl /etc/nomad.d/
sudo cp ./nomad/vault.hcl /etc/nomad.d/
sudo chown nomad:nomad /etc/nomad.d/
